### PR TITLE
Add CQM demo and tests

### LINKED ISSUE #10: Add CQM demo file

### PR DESCRIPTION
**Pull request by vgoliber**
Resolves #10

### CODE REVIEW

**Review by mcfarljm — COMMENTED** [review]
Several functions are duplicated in the DQM and CQM scripts.  I would suggest moving these functions into a module so that they can be re-used by the DQM and CQM code.  This makes it easier to maintain, since changes only need to be done in one place.  Following functions are duplicated:

- `read_in_args`
- `build_graph`: this is the same except for the node upper bound for the internet graph, which is 3000 for DQM vs 5000 for CQM.  My suggestion would be to simplify and just use the same limit for both (e.g., 3000).  Otherwise, if you want different limits, `build_graph` could accept a parameter `internet_max_nodes`, so that the code can be re-used.
- `visualize_input_graph`
- `visualize_results`

**Comment by mcfarljm** [comment]
Under "Graphs Available", the README mentions the Internet graph using between 1000 and 3000 nodes, but `demo_cqm.py` currently has an upper limit of 5000.  If `build_graph` is updated to use the same limits as suggested above, no change would be needed.

**Comment by vgoliber** [comment]
> Under "Graphs Available", the README mentions the Internet graph using between 1000 and 3000 nodes, but `demo_cqm.py` currently has an upper limit of 5000. If `build_graph` is updated to use the same limits as suggested above, no change would be needed.

This actually brings up a different issue - for CQM the number of variables limit is 5000, but each node in the graph gets 3 variables. So we need to set up a limit of 5000/3 nodes in the internet graph. I'll adjust the README and the code to reflect this.

**Review by mcfarljm — APPROVED** [review]
LGTM.  After merging, someone should make sure to update the "About" section for this repo to reference CQM instead of DQM.

**Pull request merged**
